version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xgaijvs0ejcd"
s3_prefix = "hello"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
